version: '3'

services:
  db-mysql:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identitydb
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '33061:3306'

  redis:
    image: docker.io/bitnami/redis:7.4
    environment:
      ALLOW_EMPTY_PASSWORD: yes # ALLOW_EMPTY_PASSWORD is recommended only for development.
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
    ports:
      - '63791:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local