server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:33061/identitydb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root

jwt:
  signer:
    secret-key: 3mcLqP6VR8DgRGGk/sFUZXjlOGq/meuYGmT4+JhfnrAKaItGk9qvHVoQInKxcXFb
